import Link from 'next/link';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Disclaimer & Terms | civic-duty.ai',
  description: 'Legal disclaimers, terms of use, and privacy policy for civic-duty.ai.',
};

export default function DisclaimerPage() {
  return (
    <div className="min-h-[calc(100vh-64px)] bg-white">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 sm:py-16">
        {/* Header */}
        <div className="text-center mb-12">
          <h1 className="text-4xl sm:text-5xl font-bold text-gray-900">
            Disclaimer & Terms
          </h1>
          <p className="mt-4 text-lg text-gray-600">
            Important information about using civic-duty.ai
          </p>
        </div>

        {/* Important Notice */}
        <div className="mb-12 p-6 bg-amber-50 border-2 border-amber-300 rounded-2xl">
          <div className="flex items-start">
            <svg className="w-8 h-8 text-amber-600 mr-4 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20">
              <path fillRule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clipRule="evenodd" />
            </svg>
            <div>
              <h2 className="text-xl font-bold text-amber-800 mb-2">Important Notice</h2>
              <p className="text-amber-700">
                All responses generated by civic-duty.ai are AI-simulated political perspectives 
                created for <strong>educational purposes only</strong>. These responses do not 
                represent the personal views of the creators, operators, or any individual or 
                organization. The content is designed to help users understand different political 
                worldviews, not to advocate for any particular position.
              </p>
            </div>
          </div>
        </div>

        {/* Main Content */}
        <div className="prose prose-lg max-w-none space-y-12">
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Educational Purpose</h2>
            <div className="text-gray-600 space-y-4">
              <p>
                civic-duty.ai is an educational tool designed to help users explore and understand 
                different political perspectives. The service generates AI-powered responses that 
                simulate how individuals with various political viewpoints might respond to questions.
              </p>
              <p>
                This tool is intended to:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Foster understanding of diverse political viewpoints</li>
                <li>Encourage empathy across political divides</li>
                <li>Support civic education and critical thinking</li>
                <li>Help users understand how different perspectives frame issues</li>
              </ul>
              <p>
                This tool is <strong>not</strong> intended to:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Advocate for any particular political position</li>
                <li>Provide factual news or current events information</li>
                <li>Serve as a source of political advice or guidance</li>
                <li>Replace thoughtful engagement with real people and communities</li>
              </ul>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">AI-Generated Content Disclaimer</h2>
            <div className="text-gray-600 space-y-4">
              <p>
                All political perspective responses are generated by artificial intelligence (Claude by Anthropic). 
                As such, users should be aware that:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>
                  <strong>Simulated perspectives:</strong> The responses are simulations of how 
                  someone with a particular political perspective might respond. They are not 
                  statements from actual individuals or organizations.
                </li>
                <li>
                  <strong>Not factually verified:</strong> The content is not fact-checked or 
                  verified. Users should not rely on these responses for factual information.
                </li>
                <li>
                  <strong>Generalizations:</strong> Political perspectives are complex and varied. 
                  The responses represent generalized versions of these perspectives and may not 
                  accurately represent any specific individual&apos;s views.
                </li>
                <li>
                  <strong>Potential inaccuracies:</strong> AI systems can produce content that is 
                  inaccurate, biased, or incomplete. Users should approach all responses with 
                  critical thinking.
                </li>
                <li>
                  <strong>Dynamic content:</strong> The same question may produce different 
                  responses at different times due to the nature of AI generation.
                </li>
              </ul>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Terms of Use</h2>
            <div className="text-gray-600 space-y-4">
              <p>By using civic-duty.ai, you agree to the following terms:</p>
              
              <h3 className="text-lg font-semibold text-gray-800 mt-6">Acceptable Use</h3>
              <ul className="list-disc pl-6 space-y-2">
                <li>Use the service for educational and informational purposes only</li>
                <li>Do not use generated content to spread misinformation</li>
                <li>Do not represent AI-generated content as statements from real individuals or organizations</li>
                <li>Do not use the service to harass, threaten, or harm others</li>
                <li>Respect rate limits and do not attempt to abuse the service</li>
              </ul>

              <h3 className="text-lg font-semibold text-gray-800 mt-6">Prohibited Uses</h3>
              <ul className="list-disc pl-6 space-y-2">
                <li>Generating content intended to incite violence or hatred</li>
                <li>Creating political advertisements or campaign materials</li>
                <li>Attempting to circumvent content moderation or ethical guardrails</li>
                <li>Using the service for any illegal purpose</li>
                <li>Scraping or automated collection of responses</li>
              </ul>

              <h3 className="text-lg font-semibold text-gray-800 mt-6">Limitation of Liability</h3>
              <p>
                civic-duty.ai and its operators are not liable for any damages, losses, or 
                consequences arising from the use of this service or the content generated. 
                The service is provided &quot;as is&quot; without warranties of any kind.
              </p>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Privacy Policy</h2>
            <div className="text-gray-600 space-y-4">
              <h3 className="text-lg font-semibold text-gray-800">Data Collection</h3>
              <p>
                civic-duty.ai collects minimal data necessary for the service to function:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Questions submitted to the service (not linked to personal identifiers)</li>
                <li>Basic usage analytics (page views, feature usage)</li>
                <li>Technical data (IP addresses for rate limiting, browser type for compatibility)</li>
              </ul>

              <h3 className="text-lg font-semibold text-gray-800 mt-6">Data Retention</h3>
              <p>
                Questions and responses are processed in real-time and are not permanently stored 
                or associated with individual users. Rate limiting data is retained temporarily 
                to prevent abuse.
              </p>

              <h3 className="text-lg font-semibold text-gray-800 mt-6">Third-Party Services</h3>
              <p>
                This service uses Anthropic&apos;s Claude API to generate responses. Questions submitted 
                to civic-duty.ai are sent to Anthropic for processing. Please refer to 
                Anthropic&apos;s privacy policy for information about their data practices.
              </p>

              <h3 className="text-lg font-semibold text-gray-800 mt-6">No Account Required</h3>
              <p>
                civic-duty.ai does not require user accounts or authentication. No personal 
                information is collected or stored beyond what is necessary for basic service 
                operation.
              </p>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Content Guidelines</h2>
            <div className="text-gray-600 space-y-4">
              <p>
                Our AI system is designed with ethical guardrails to prevent the generation of 
                harmful content. All perspectives are represented with the following constraints:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>No calls for violence or harm against individuals or groups</li>
                <li>No hate speech, slurs, or dehumanizing language</li>
                <li>No content that promotes illegal activities</li>
                <li>No content that could be used for harassment or threats</li>
                <li>Conspiracy theories are labeled as disputed or controversial when referenced</li>
              </ul>
              <p className="mt-4">
                If you encounter content that you believe violates these guidelines, please 
                contact us.
              </p>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Changes to Terms</h2>
            <div className="text-gray-600">
              <p>
                We reserve the right to modify these terms, disclaimers, and privacy policy at 
                any time. Continued use of the service after changes constitutes acceptance of 
                the updated terms.
              </p>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Contact</h2>
            <div className="text-gray-600">
              <p>
                If you have questions about these terms or the service, please reach out through 
                the appropriate channels.
              </p>
            </div>
          </section>

          {/* Acknowledgment */}
          <section className="p-6 bg-gray-50 rounded-2xl">
            <h2 className="text-xl font-bold text-gray-900 mb-4">Acknowledgment</h2>
            <p className="text-gray-600">
              By using civic-duty.ai, you acknowledge that you have read, understood, and agree 
              to be bound by these terms and disclaimers. You understand that the content generated 
              is AI-simulated and for educational purposes only.
            </p>
            <div className="mt-6 flex flex-col sm:flex-row gap-4">
              <Link 
                href="/explore"
                className="inline-flex items-center justify-center px-6 py-3 font-semibold text-white bg-gradient-to-r from-blue-600 to-purple-600 rounded-xl hover:from-blue-700 hover:to-purple-700 transition-all"
              >
                I Understand - Start Exploring
              </Link>
              <Link 
                href="/"
                className="inline-flex items-center justify-center px-6 py-3 font-semibold text-gray-700 bg-white border-2 border-gray-200 rounded-xl hover:border-gray-300 hover:bg-gray-50 transition-all"
              >
                Return to Home
              </Link>
            </div>
          </section>
        </div>

        {/* Last Updated */}
        <div className="mt-12 text-center text-sm text-gray-500">
          Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
        </div>
      </div>
    </div>
  );
}
